global:
  resolve_timeout: 1m

receivers:
  - name: 'webhook_receiver'
    webhook_configs:
      - url: 'https://webhook.site/b1484664-cdfc-43fa-861c-7d17075900f4'

route:
  group_by: ['alertname']
  receiver: 'webhook_receiver'
  routes:
    - match:
        alertname: 'SiteDown'
      receiver: 'webhook_receiver'